version: '3.8'

services:
    mongodb-test:
        image: mongo:4.4.6
        container_name: mongodb-test
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db

    redis-test:
        image: redis:6.2.3
        container_name: redis-test
        ports:
            - "6379:6379"
