version: '3.8'

services:
    mongodb-test:
        image: mongo:4.4.6
        container_name: mongodb-test
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db

    redis-test:
        image: redis:6.2.3
        container_name: redis-test
        ports:
            - "6379:6379"

    backend-app:
        build:
            context: ./dotnetbackened
            dockerfile: Dockerfile
        container_name: backend-app
        ports:
            - "127.0.0.1:3001:80"
        depends_on:
            - mongodb-test
            - redis-test
        environment:
            - ASPNETCORE_ENVIRONMENT=Container
        
